linters-settings:
  lll:
    line-length: 120
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  unparam:
    check-exported: false
  goconst:
    min-len: 2
    min-occurrences: 2
  maligned:
    suggest-new: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  misspell:
    locale: US
issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: internal/mocks/entities/mock_entities.go
      linters:
        - dupl
    - path: cmd/api/main.go
      linters:
        - gochecknoglobals
      # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "
run:
  tests: false # run linter on test files
  deadline: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
#    - gocritic TODO: evaluate others errors
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - asciicheck
    - gochecknoglobals
    - gocognit
    - godot
    - maligned
    - nestif
    - prealloc
    - testpackage
    - wsl
  # - goerr113

  # don't enable:
  # - godox
  # - funlen
